# Generated by Django 5.1.1 on 2024-11-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=155),
        ),
    ]
