# Generated by Django 5.1.3 on 2024-12-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_order', '0003_order_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'در حال انتظار'), ('paid', 'پرداخت شده')], default='pending', max_length=155),
        ),
    ]
