# Generated by Django 5.1.1 on 2024-12-07 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_order', '0005_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='fax',
        ),
    ]
