# Generated by Django 5.1.3 on 2024-12-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_banner_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'banner', 'verbose_name_plural': 'بنر ها'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'color', 'verbose_name_plural': 'رنگ ها'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'gallery', 'verbose_name_plural': 'گالری'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'product', 'verbose_name_plural': 'محصول ها'},
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
