# Generated by Django 4.2 on 2024-12-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_delete_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(height_field=150, upload_to='galleries', width_field=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(height_field=150, upload_to='products', width_field=100),
        ),
    ]
