# Generated by Django 5.1.3 on 2024-12-10 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_delete_banner'),
        ('product_slider', '0002_alter_slider_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='banners', verbose_name='عکس')),
                ('link', models.URLField()),
                ('order', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='ترتیب')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'بنر ها',
            },
        ),
    ]
