# Generated by Django 4.2 on 2024-12-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('img', models.ImageField(height_field=150, upload_to='about_us', width_field=100)),
            ],
            options={
                'verbose_name': 'AboutUS',
                'verbose_name_plural': 'درباره ما',
            },
        ),
    ]
