# Generated by Django 4.2 on 2024-12-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='img',
            field=models.ImageField(blank=True, height_field=150, null=True, upload_to='about_us', width_field=100),
        ),
    ]
